accounts/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^doc/$', views.doc, name='doc'),
    url(r'^dload/$', views.dload, name='dload'),
    url(r'^news/$', views.news, name='news'),
    url(r'^login/$', auth_views.LoginView, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/success/$', views.register_success, name='reg_suc'),
    # url(r'^logout/$', views.logout_page, {'next_page': 'accounts/index.html'}, name='logout'),
    url(r'^logout/$', auth_views.LogoutView, {'next_page': '/home/login'}, name='logout'),
]

anot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from anot import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('accounts.urls')),
    url(r'^family/', include('family.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

family/urls.py
from django.conf.urls import url
from . import views
from anot import settings
from django.conf.urls.static import static
import random


app_name = 'family'
# userid = ''.join(random.choice('0123456789ABCDEF') for i in range(16))
# userid = "MMMM"

urlpatterns = [
    url('^$', views.index, name='index'),
    url(r'^results/$', views.results, name='results'),
    url(r'^results/download_enrich/$', views.download_enrich, name='download_enrich'),
    url(r'^results/download_all/$', views.download_all, name='download_all'),
    url(r'^results/download_fig/$', views.download_fig, name='download_fig'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
import random

from django.db import models

accounts/views.py
#views.py
# here .form is required for python 3
# form only will work with python 2
# from .form import RegistrationForm, User
# from .models import user
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.shortcuts import render
import random
# from django.core.urlresolvers import reverse
from django.urls import reverse


# @login_required
def index(request):
    return render(request, 'accounts/index.html', {'user': request.user})


def doc(request):
    return render(request, 'accounts/doc.html', {'user': request.user})


def dload(request):
    return render(request, 'accounts/dload.html', {'user': request.user})

def news(request):
    return render(request, 'accounts/news.html', {'user': request.user})

def register(request):
    form = RegistrationForm(request.POST or None)

    if form.is_valid():
        user = User.objects.create_user(username=form.cleaned_data['username'],
                                        password=form.cleaned_data['password1'],
                                        email=form.cleaned_data['email']
                                            )

        context = {'form': RegistrationForm(),
                   'reply': 'You Have Registered Successfully'}
        messages.success(request, "You Have Registered Successfully!")
        return HttpResponseRedirect(reverse("accounts:register"))
    else:
        # context = {'form': RegistrationForm()}
        return render(request, 'accounts/register.html', {'form':form})


def register_success(request):
    return render(request, 'accounts/success.html')

accounts/templates/accounts/dload.html
{% extends 'accounts/header.html' %}
{% load bootstrap %}

<title>{% block title %}Family Enrichment Analysis{% endblock %}</title>

{% block body %}
    <div class="container">
        <h4><b>Download source code and database using git</b></h4>

        <code> git clone https://github.com/reneshbedre/GenFam.git </code>
        <br><br>

         <button type="button" class="btn btn-default">
                <a href="https://github.com/reneshbedre/GenFam" target="_blank" style="color:#DEB887; text-decoration: none;">Visit GenFam Source Code and Database</a>
            </button>
        <br>

        <h4><b>Direct download source code and database using git</b></h4>
        <ul>
            <li><b>Version 1.1 release Oct 31, 2019 (release for minor changes)</b></li>
            <br>
            <button type="button" class="btn btn-default">
                <a href="{{MEDIA_URL}}src/GenFam_src_v1.1.tar.gz" target="_blank" style="color:#DEB887; text-decoration: none;">Source code</a>
            </button>
            <br>
                <ul>
                    <li>Enriched gene families are ranked as per FDR values</li>
                    <li>The format of P-value and FDR changed in scientific notation</li>
                </ul>
            <br>
            <li><b>Version 1.0 </b></li>
            <br>
            <button type="button" class="btn btn-default">
                <a href="{{MEDIA_URL}}src/GenFam_src.tar.gz" target="_blank" style="color:#DEB887; text-decoration: none;">Source code and database</a>
            </button>

        </ul>

    </div>

        {% include 'accounts/footer.html' %}


        <!-- footer
        <div class="container">
        {% include 'accounts/footer.html' %}
        </div>
        -->

{% endblock %}
</title>
</head>
<body>

</body>
</html>

accounts/templates/accounts/doc.html
{% extends 'accounts/header.html' %}
{% load bootstrap %}

<title>{% block title %}Family Enrichment Analysis{% endblock %}</title>

{% block body %}
    <div class="container">
        <h4><b>Quick start analysis guide</b></h4>
        <br>
        <ol>
            <li><b>Input the list of gene IDs in <font color="red">Sequence IDs</font> form
            </b></li>
            <br>
            <p>Paste the list of genes in Sequence IDs form. Each line should contain one gene ID
                as per Phytozome v12.0 database format. You can check the allowed IDs for each plant species on the
                analysis
                page. <br><br> For example, allowed IDs for Rice (<i>Oryza sativa</i>) are, <br><br>
                Phytozome locus: LOC_Os01g06882 <br> Phytozome transcript: LOC_Os01g06882.1 <br> Phytozome pacID:
                24120792</p>
            <br>

            <li><b>Select <font color="red">plant species</font> from dropdown menu</b></li>
            <br>
            <p>Select plant species corresponding to the gene IDs. Currently, GenFam
                supports analysis of sixty plant genomes.</p>
            <br>
            <li><b>Select <font color="red">plant ID type</font> from dropdown menu</b></li>
            <br>
            <p>Select the plant ID type for respective plant species. Please, refere step 1 for allowed IDs type for
            GenFam analysis. Note: Do not combine different ID types while performing enrichment analysis.</p>

            <br>
            <li><b>Select <font color="red">statistical significance test</font> from enrichment analysis</b></li>
            <br>
            <p>Select the statistical significance test from dropdown menu. Currently, GenFam supports four tests for
                enrichment analysis including, <b><i>Fisher exact test</i>, <i>Hypergeometric distribution</i>, <i>Binomial
                    distribution</i> and <i>Chi-squared distribution</i></b>, thus providing flexibility in the analysis
                based on the sample size and user preferences.</p>
            <p>We recommend using Fisher exact test, chi-square test and hypergeometric distribution for smaller
                datasets (< 1000 gene IDs), and binomial distribution for larger datasets.</p>

            <br>
            <li><b>Select <font color="red">multiple testing correction</font> for enrichment analysis</b></li>
            <br>
            <p>Select the  multiple testing correction test from dropdown menu. GenFam supports Bonferroni,
                Bonferroni-Holm and Benjamini-Hochberg tests for correcting P-values.</p>

            <br>
            <li><b>Select <font color="red">Run</font> to perform enrichment analysis</b></li>
            <br>
            <p>Once all parameters selected, click run to perform the analysis.</p>

            <br>
            <li><b>GenFam enrichment ouput</b></li>
            <br>
            <p>If enrichment analysis is performed successfully, you will receive a message <font color="red">"Success!
                Data Analysis Completed"</font>.</p>
            <p>You can obtain results for <b>All Enriched Families</b>, <b>All Gene Families</b> and <b>Get Figures</b></p>
            <p>"All Enriched Families" file contain results for gene families enriched with P-value < 0.05. "All Gene
                Families" file contain results for all gene families which are classified based on user dataset.
                Get figures will generate the bar graph of
            enriched gene families.</p>

        </ol>
        <br><br><br><br>

    </div>

        {% include 'accounts/footer.html' %}


        <!-- footer
        <div class="container">
        {% include 'accounts/footer.html' %}
        </div>
        -->

{% endblock %}

accounts/templates/accounts/footer.html
<nav class="container footer navbar-fixed-bottom">

       		 <p align="center" style="color:#FFF0F5;font-size:11px">Mandadi Lab, Texas A&M AgriLife Research and
                 Extension Center <br> &copy; All Rights Reserved  <br> <font color="yellow">Site developed
				 and maintained by <a href="https://reneshbedre.github.io/" target="_blank" style="color:yellow"><u>
				 Renesh Bedre</u></a></font>
			 </p>
</nav>

accounts/templates/accounts/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Add{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Yatra+One" rel="stylesheet">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}"/>

    <!-- Begin Inspectlet JS Code -->
    <script type="text/javascript" id="inspectletjs">
    (function() {
     var insp_ab_loader = true; // set this boolean to false to disable the A/B testing loader
    window.__insp = window.__insp || [];
    __insp.push(['wid', 1575448564]);
    var ldinsp = function(){
    if(typeof window.__inspld != "undefined") return; window.__inspld = 1; var insp = document.createElement('script'); insp.type = 'text/javascript'; insp.async = true; insp.id = "inspsync"; insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cdn.inspectlet.com/inspectlet.js?wid=1575448564&r=' + Math.floor(new Date().getTime()/3600000); var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(insp, x);if(typeof insp_ab_loader != "undefined" && insp_ab_loader){ var adlt = function(){ var e = document.getElementById('insp_abl'); if(e){ e.parentNode.removeChild(e); __insp.push(['ab_timeout']); }}; var adlc = "body{ visibility: hidden !important; }"; var adln = typeof insp_ab_loader_t != "undefined" ? insp_ab_loader_t : 1200; insp.onerror = adlt; var abti = setTimeout(adlt, adln); window.__insp_abt = abti; var abl = document.createElement('style'); abl.id = "insp_abl"; abl.type = "text/css"; if(abl.styleSheet) abl.styleSheet.cssText = adlc; else abl.appendChild(document.createTextNode(adlc)); document.head.appendChild(abl); } };
    setTimeout(ldinsp, 0);
    })();
    </script>
    <!-- End Inspectlet JS Code -->

</head>
<body>
    <!-- navbar starts here -->
    <div class="container">
    <nav class="navbar navbar-static-top">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'accounts:index' %}" style="color:#FFF0F5;">GenFam</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'family:index' %}" style="color:#FFF0F5;">Analysis</a></li>
            <li><a href="{% url 'accounts:doc' %}" style="color:#FFF0F5;">Documentation</a></li>
            <li><a href="{% url 'accounts:dload' %}" style="color:#FFF0F5;">Downloads</a></li>
            <li><a href="{% url 'accounts:news' %}" style="color:#FFF0F5;">News</a></li>

            <!--
            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}" style="color:#FFF0F5;">
                    <span class="glyphicon glyphicon-log-out"></span>
                        &nbsp;Logout</a></li>
                    <p class="navbar-text" style="color:#A52A2A;font-weight: bold;"><span class="glyphicon  glyphicon-user"></span>&nbsp;
                        Welcome {{ user.username }}!</p>
            {% else %}
                <li><a href="{% url 'accounts:login' %}" style="color:#FFF0F5;">
                    <span class="glyphicon glyphicon-log-in"></span>
                        &nbsp;Login</a></li>
            {% endif %}
            -->
        </ul>
        <!-- search box -->
        <!--
        <form class="navbar-form pull-right" role="search" method="get" action="http://www.google.com/search">
                <input class="form-control" type="text" placeholder="Search" name="q">
                <button class="btn btn-online-success" type="Submit">Search</button>
                <input type="hidden" name="sitesearch" value="http://mandadilab.webfactional.com/home" />
        </form>
        -->
    </nav>
    </div>
    <!-- navbar ends here -->

{% block body %}
{% endblock %}

</body>
</html>

accounts/templates/accounts/index.html
{% extends 'accounts/header.html' %}
{% load bootstrap %}
{% load staticfiles %}

<!-- tab title -->
{% block title %}Welcome to GenFam Project{% endblock %}

{% block body %}

        <div class="container">
            <div class="row">
                <div class="col-md-6">

		<h5><b>GenFam is also available as <a href='https://reneshbedre.github.io/blog/genfam.html'>command line interface</a></b></h5>

           
		<br>
		 <h4><b>GenFam: Gene Family based classification and enrichment analysis</b></h4>
            <p>GenFam is a comprehensive classification and enrichment analysis tool for plant genomes. It is
                a user-friendly web application providing unique way to characterize the large-scale gene datasets such as
                        those from transcriptome analysis.</p>
            <ul>
                <li>New functional classification and enrichment approach, where plant gene families are used to identify
                    overrepresented gene functions</li>
                <br>
                <li>Web based and easy to handle graphical-user interface which allows users to readily input gene lists,
                    and export results in both tabular and graphical formats</li>
                 <br>
                <li>Statistical parameters can be customized as per user interest and data type</li>
                 <br>
                <li>Currently supports sixty plant genomes and gene identifiers that are available on
                    Phytozome v12.0 database</li>
            </ul>
                     <br>
            <p>To perform analysis <a href="{% url 'family:index' %}">click here</a></p>
                    <br>
                    <h6><b>How to cite:</b></h6>
                    <p>Bedre, R, Mandadi, K. GenFam: A web application and database for gene family‐based
                        classification and functional enrichment analysis. Plant Direct. 2019; 3: 1– 7.
                        https://doi.org/10.1002/pld3.191</p>
            </div>
                <div class="col-md-6">
                    <img src="{% static 'accounts/fam_enrich_out.png' %}" height="580px" width="560px">
                </div>
            </div>
            </div>
            <br><br><br><br>
            <br><br><br><br>


        {% include 'accounts/footer.html' %}



{% endblock %}

accounts/templates/accounts/log_out.html
{% extends 'accounts/header.html' %}
{% load bootstrap %}

{% block title %}Log Out{% endblock %}
{% block body %}
    <!--
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    -->
    <div class="container">
        <div class="col-md-4">
            {{ reply }}
        </div>
    </div>
    <br>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/header.html' %}
{% load bootstrap %}

{% block title %}Login{% endblock %}
{% block body %}
    <!--
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    -->
    <div class="container">
        <div class="col-md-4 col-md-offset-3" style="top:70px;">
            <p class="bg-danger" style="padding:10px 10px 10px 15px;">You must login or register to use GenFam</p>
            <h2>Login to GenFam</h2>
            <br>
             <form method="post" action=".">{% csrf_token %}
                {{ form | bootstrap }}
                 <button type="submit" class="btn btn-success">Login</button>
                 <input type="hidden" name="next" value="/home" />
             </form>
            <br>
            <button type="submit" class="btn btn-info"><a href="{% url 'accounts:register' %}"
                                                             style="color:#F8F8FF; text-decoration: none;">
                Register</a></button>
        </div>
    </div>
    <br>

        {% include 'accounts/footer.html' %}


{% endblock %}

accounts/templates/accounts/news.html
{% extends 'accounts/header.html' %}
{% load bootstrap %}
{% load staticfiles %}

<!-- tab title -->
{% block title %}GenFam News{% endblock %}

{% block body %}

<div class="container">
    <ul class="list-group">
	<li class="list-group-item">Oct 10, 2020: <a href="https://reneshbedre.github.io/blog/genfam.html">Command line interface</a> of
            GenFam Released</li>
        <li class="list-group-item">March 20, 2020: <a href="https://github.com/reneshbedre/GenFam">
            GenFam project</a> (source code and database) available at GitHub</li>
        <li class="list-group-item">Dec 4, 2019: <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/pld3.191">
            GenFam</a> published in Plant Direct journal</li>
        <li class="list-group-item">Oct 31, 2019: <a href="http://mandadilab.webfactional.com/home/dload/">V1.1</a> of
            GenFam Released</li>
    </ul>
</div>

{% include 'accounts/footer.html' %}

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/header.html' %}
{% load bootstrap %}

{% block title %}User Registration{% endblock %}

{% block body %}
    <div class="container">
        <div class="col-md-4 col-md-offset-3" style="top:30px;">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error }}</strong>
                    </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error }}</strong>
                    </div>
                {% endfor %}
            {% endif %}


            {% if messages %}
               {% for message in messages %}
                    <div class="alert alert-info" >
                        <p><strong>{{ message }}<strong</p>
                    </div>
                {% endfor %}
            {% endif %}

            <form method="post" action="{% url 'accounts:register' %}">
                {% csrf_token %}
                {{ form | bootstrap }}
              <button type="submit" class="btn btn-success">Register</button>
            </form>
            <br>

            <button class="btn btn-info"><a href="{% url 'accounts:login' %}"
                                                   style="color:#F8F8FF; text-decoration: none;">Login</a></button>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/success.html
{% extends 'add/header.html' %}
{% load bootstrap %}

{% block title %}Registration Successful{% endblock %}

{% block body %}
    <p>Thank you for registering.</p>
    <a href="/">Login</a> 
{% endblock %}